HEADERS = \
	include/AutoIndex.hpp \
	include/buffer.hpp \
	include/CGI.hpp \
	include/ConfigParser.hpp \
	include/Connection.hpp \
	include/cpp109.hpp \
	include/defines.hpp \
	include/EnvironmentMap.hpp \
	include/FD.hpp \
	include/HTTP.hpp \
	include/Listener.hpp \
	include/Location.hpp \
	include/logger.hpp \
	include/MIME.hpp \
	include/Poller.hpp \
	include/Request.hpp \
	include/Response.hpp \
	include/Server.hpp \
	include/SourceFds.hpp \
	include/stringutils.hpp \
	include/syscalls.hpp \
	include/utils.hpp \
