SOURCES = \
	src/Server/overwrite.cpp \
	src/Server/Location.cpp \
	src/Server/Listener.cpp \
	src/Server/Server.cpp \
	src/main.cpp \
	src/Utils/MIME.cpp \
	src/Utils/IO.cpp \
	src/Utils/utils.cpp \
	src/Utils/methods.cpp \
	src/Utils/FD.cpp \
	src/Utils/file.cpp \
	src/Utils/syscalls.cpp \
	src/Utils/stringutils.cpp \
	src/Handling/buf.cpp \
	src/Handling/Request.cpp \
	src/Handling/Response/ResponseHandling.cpp \
	src/Handling/Response/ResponseIO.cpp \
	src/Handling/Response/ResponseCGI.cpp \
	src/Handling/Response/ResponseChunk.cpp \
	src/Handling/Response/Response.cpp \
	src/Handling/Response/ResponseErrors.cpp \
	src/Handling/HTTP.cpp \
	src/Handling/AutoIndex.cpp \
	src/CGI/EnvironmentMap.cpp \
	src/CGI/CGI.cpp \
	src/Config/FiniteStateMachine.cpp \
	src/Config/CheckValidity.cpp \
	src/Config/DebugPrint.cpp \
	src/Config/init.cpp \
	src/Config/Parser.cpp \
	src/Polling/Connection.cpp \
	src/Polling/Poller.cpp \
	src/Polling/SourceFds.cpp \
