SOURCES = \
	src/AutoIndex.cpp \
	src/buf.cpp \
	src/CGI.cpp \
	src/Config/CheckValidity.cpp \
	src/Config/DebugPrint.cpp \
	src/Config/FiniteStateMachine.cpp \
	src/Config/init.cpp \
	src/Config/Parser.cpp \
	src/Connection.cpp \
	src/EnvironmentMap.cpp \
	src/FD.cpp \
	src/HTTP.cpp \
	src/Listener.cpp \
	src/Location.cpp \
	src/main.cpp \
	src/methods.cpp \
	src/MIME.cpp \
	src/Poller.cpp \
	src/Request.cpp \
	src/Response/Response.cpp \
	src/Response/ResponseCGI.cpp \
	src/Response/ResponseChunk.cpp \
	src/Response/ResponseErrors.cpp \
	src/Response/ResponseIO.cpp \
	src/Server.cpp \
	src/SourceFds.cpp \
	src/stringutils.cpp \
	src/syscalls.cpp \
	src/utils.cpp \
