SOURCES = \
	src/buf.cpp \
	src/CGI.cpp \
	src/Config/CheckValidity.cpp \
	src/Config/DebugPrint.cpp \
	src/Config/FiniteStateMachine.cpp \
	src/Config/Parser.cpp \
	src/Connection.cpp \
	src/EnvironmentMap.cpp \
	src/HTTP.cpp \
	src/Listener.cpp \
	src/Location.cpp \
	src/main.cpp \
	src/MIME.cpp \
	src/Poller.cpp \
	src/Request.cpp \
	src/Response.cpp \
	src/ResponseChunk.cpp \
	src/Server.cpp \
	src/stringutils.cpp \
	src/utils.cpp \
